import Mathlib
import Architect

/-!
# Word balls of a hidden-layer class

The hidden-layer class `F ⊆ (X → X)` generates the depth-`k` class
`B(k,F) = {f_m ∘ ⋯ ∘ f_1 : 0 ≤ m ≤ k, f_i ∈ F}` (with `B(0,F) = {id}`), the word ball of
radius `k` of the semigroup (monoid) `⟨F⟩ = ⋃_k B(k,F)`.

We define `B(k,F)` recursively by `B(k+1,F) = B(k,F) ∪ F ∘ B(k,F)` and record its basic
properties (monotonicity, closure under composition, cardinality bounds).
-/

namespace LeanDeepgen

variable {X : Type*}

@[blueprint "def:word-ball"
  (statement := /-- Let $F \subseteq \mathcal X^{\mathcal X}$ be a hidden-layer class.
    The depth-$k$ hidden class is the word ball
    $B(k,F) = \{f_m \circ \cdots \circ f_1 : 0 \le m \le k,\ f_i \in F\}$,
    with $B(0,F) = \{\mathrm{id}\}$.
    It is defined recursively by $B(k+1,F) = B(k,F) \cup F \circ B(k,F)$. -/)]
def wordBall (F : Set (X → X)) : ℕ → Set (X → X)
  | 0 => {id}
  | k + 1 => wordBall F k ∪ Set.image2 (fun g f => g ∘ f) F (wordBall F k)

@[blueprint "def:words"
  (statement := /-- The words of length exactly $m$:
    $F^m = \{f_m \circ \cdots \circ f_1 : f_i \in F\}$,
    with $F^0 = \{\mathrm{id}\}$ and $F^{m+1} = F \circ F^m$. -/)]
def words (F : Set (X → X)) : ℕ → Set (X → X)
  | 0 => {id}
  | m + 1 => Set.image2 (fun g f => g ∘ f) F (words F m)

@[blueprint "def:semigroup-closure"
  (statement := /-- The semigroup (monoid) generated by $F$ is
    $\langle F\rangle = \bigcup_{k \ge 0} B(k,F)$. -/)]
def semigroupClosure (F : Set (X → X)) : Set (X → X) := ⋃ k, wordBall F k

variable {F G : Set (X → X)} {k l : ℕ} {f g : X → X}

@[simp, blueprint "lem:wordball-zero"
  (statement := /-- $B(0,F) = \{\mathrm{id}\}$. -/)]
theorem wordBall_zero : wordBall F 0 = {id} := rfl

@[blueprint "lem:wordball-succ"
  (statement := /-- $B(k+1,F) = B(k,F) \cup \{g \circ f : g \in F,\ f \in B(k,F)\}$. -/)]
theorem wordBall_succ :
    wordBall F (k + 1) = wordBall F k ∪ Set.image2 (fun g f => g ∘ f) F (wordBall F k) := rfl

@[blueprint "lem:id-mem-wordball"
  (statement := /-- $\mathrm{id} \in B(k,F)$ for every $k$. -/)]
theorem id_mem_wordBall : id ∈ wordBall F k := by
  /-- Induction on $k$: $\mathrm{id} \in B(0,F)$ and $B(k,F) \subseteq B(k+1,F)$. -/
  induction k with
  | zero => simp
  | succ k ih => exact Or.inl ih

@[blueprint "lem:wordball-mono"
  (statement := /-- The word balls are increasing: $B(k,F) \subseteq B(k+1,F)$, hence
    $B(k,F) \subseteq B(l,F)$ for $k \le l$. -/)]
theorem wordBall_mono : Monotone (wordBall F) :=
  monotone_nat_of_le_succ fun _ => Set.subset_union_left

@[blueprint "lem:mem-wordball-succ"
  (statement := /-- If $g \in F$ and $f \in B(k,F)$ then $g \circ f \in B(k+1,F)$. -/)]
theorem mem_wordBall_succ_of_mem_of_mem (hg : g ∈ F) (hf : f ∈ wordBall F k) :
    g ∘ f ∈ wordBall F (k + 1) :=
  Or.inr ⟨g, hg, f, hf, rfl⟩

@[blueprint "lem:subset-semigroup-closure"
  (statement := /-- $B(k,F) \subseteq \langle F \rangle$ for every $k$. -/)]
theorem subset_semigroupClosure : wordBall F k ⊆ semigroupClosure F :=
  Set.subset_iUnion (wordBall F) k

@[blueprint "lem:wordball-subset-of-subset"
  (statement := /-- If $F \subseteq G$ then $B(k,F) \subseteq B(k,G)$. -/)]
theorem wordBall_subset_wordBall_of_subset (h : F ⊆ G) : wordBall F k ⊆ wordBall G k := by
  /-- Induction on $k$, using that $\circ$-images are monotone in both arguments. -/
  induction k with
  | zero => exact le_rfl
  | succ k ih => exact Set.union_subset_union ih (Set.image2_subset h ih)

@[blueprint "lem:comp-mem-wordball-add"
  (statement := /-- If $f \in B(k,F)$ and $g \in B(l,F)$ then $g \circ f \in B(l+k,F)$. -/)]
theorem comp_mem_wordBall_add (hf : f ∈ wordBall F k) (hg : g ∈ wordBall F l) :
    g ∘ f ∈ wordBall F (l + k) := by
  /-- Induction on $l$ (the length of the word $g$). If $g = \mathrm{id}$ this is $f \in B(k,F)$;
    if $g = a \circ b$ with $a \in F$, $b \in B(l,F)$ then $g \circ f = a \circ (b \circ f)$ with
    $b \circ f \in B(l+k,F)$ by induction. -/
  induction l generalizing g with
  | zero =>
    simp only [wordBall_zero, Set.mem_singleton_iff] at hg
    subst hg
    simpa using hf
  | succ l ih =>
    rcases hg with hg | ⟨a, ha, b, hb, hab⟩
    · exact wordBall_mono (by omega : l + k ≤ l + 1 + k) (ih hg)
    · rw [← hab, Nat.succ_add]
      exact mem_wordBall_succ_of_mem_of_mem (g := a) (f := b ∘ f) ha (ih hb)

@[blueprint "lem:wordball-succ-eq-union-words"
  (statement := /-- $B(k+1,F) = B(k,F) \cup F^{k+1}$: the word ball of radius $k+1$ is the word
    ball of radius $k$ together with the words of length exactly $k+1$. -/)]
theorem wordBall_succ_eq_union_words : wordBall F (k + 1) = wordBall F k ∪ words F (k + 1) := by
  /-- Induction on $k$: $F \circ B(k+1,F) = F \circ B(k,F) \cup F \circ F^{k+1}$ and
    $F \circ B(k,F) \subseteq B(k+1,F)$. -/
  induction k with
  | zero => rfl
  | succ k ih =>
    have h1 : Set.image2 (fun g f => g ∘ f) F (wordBall F k) ⊆ wordBall F (k + 1) :=
      Set.subset_union_right
    calc wordBall F (k + 1 + 1)
        = wordBall F (k + 1) ∪
            Set.image2 (fun g f => g ∘ f) F (wordBall F k ∪ words F (k + 1)) := by
          rw [wordBall_succ, ← ih]
      _ = wordBall F (k + 1) ∪
            (Set.image2 (fun g f => g ∘ f) F (wordBall F k) ∪ words F (k + 1 + 1)) := by
          rw [Set.image2_union_right]; rfl
      _ = wordBall F (k + 1) ∪ words F (k + 1 + 1) := by
          rw [← Set.union_assoc, Set.union_eq_left.mpr h1]

@[blueprint "lem:words-encard-le"
  (statement := /-- $|F^m| \le |F|^m$ (as extended natural numbers). -/)]
theorem encard_words_le : (words F k).encard ≤ F.encard ^ k := by
  /-- Induction on $k$: $F^{k+1}$ is the image of $F \times F^k$ under composition. -/
  induction k with
  | zero => simp [words]
  | succ k ih =>
    calc (words F (k + 1)).encard
        = ((fun p : (X → X) × (X → X) => p.1 ∘ p.2) '' (F ×ˢ words F k)).encard := by
          rw [words, Set.image_prod]
      _ ≤ (F ×ˢ words F k).encard := Set.encard_image_le _ _
      _ = F.encard * (words F k).encard := Set.encard_prod
      _ ≤ F.encard * F.encard ^ k := by gcongr
      _ = F.encard ^ (k + 1) := by ring

@[blueprint "lem:wordball-encard-le"
  (statement := /-- $|B(k,F)| \le \sum_{m=0}^{k} |F|^m$ (as extended natural numbers). -/)]
theorem encard_wordBall_le : (wordBall F k).encard ≤ ∑ m ∈ Finset.range (k + 1), F.encard ^ m := by
  /-- Induction on $k$ using $B(k+1,F) = B(k,F) \cup F^{k+1}$ and $|F^{k+1}| \le |F|^{k+1}$. -/
  induction k with
  | zero => simp
  | succ k ih =>
    rw [wordBall_succ_eq_union_words, Finset.sum_range_succ]
    exact (Set.encard_union_le _ _).trans (add_le_add ih encard_words_le)

@[blueprint "lem:wordball-card"
  (statement := /-- If $F$ is finite with $|F| = r \ge 2$ then
    $|B(k,F)| \le \sum_{m=0}^k r^m \le r^{k+1}$. -/)]
theorem encard_wordBall_le_pow {r : ℕ} (hF : F.Finite) (hr : F.ncard = r) (h2 : 2 ≤ r) :
    (wordBall F k).encard ≤ (r : ℕ∞) ^ (k + 1) := by
  /-- Combine the previous bound with the geometric sum estimate
    $\sum_{m \le k} r^m = (r^{k+1}-1)/(r-1) < r^{k+1}$ for $r \ge 2$. -/
  have hFe : F.encard = (r : ℕ∞) := by rw [← hr, hF.cast_ncard_eq]
  refine encard_wordBall_le.trans ?_
  rw [hFe]
  have h := (Nat.geomSum_lt h2 (s := Finset.range (k + 1)) (n := k + 1)
    (fun m hm => Finset.mem_range.mp hm)).le
  exact_mod_cast h

end LeanDeepgen
