import Mathlib
import Architect
import LeanDeepgen.Setting.WordBall
import LeanDeepgen.Setting.Metrics
import LeanDeepgen.Setting.Covering
import LeanDeepgen.Growth.Defs
import LeanDeepgen.Growth.ArzelaAscoli

/-!
# Saturation conditions P1 and P1' (paper Sec. 4 / App. F)

* `cond:p1` (P1, equicontinuous semigroup on a compact domain saturates): if `𝒳` is compact and
  the semigroup `⟨F⟩` is precompact in `d_∞` (1), equicontinuous (2a), uniformly Lipschitz (2b),
  or generated by non-expanding maps (2c), then
  `N^ext(B(k,F), d_∞, ε) ≤ N^ext(cl ⟨F⟩, d_∞, ε) < ∞` for all `ε > 0` and all `k`.
  The four hypotheses are stated as four theorems `cond_p1_of_totallyBounded`,
  `cond_p1_of_equicontinuous`, `cond_p1_of_uniformLipschitz`, `cond_p1_of_nonexpanding`,
  proved by (2c) ⇒ (2b) ⇒ (2a) ⇒ (1) ⇒ conclusion (the last step via `thm:caa`).
* `cond:p1-ucont` (P1', contraction to a compact invariant set): uniformly `c`-contracting
  generators (`c < 1`), a nonempty invariant set `A`, and a bounded set `K` absorbing all words
  of length `L`. Then for `m(ε) = L + ⌈log_{1/c}(2 diam K / ε)⌉` (`memoryLength`, defined in
  `LeanDeepgen.Growth.Defs`) and every `k ≥ m(ε)`,
  `N^ext(B(k,F), d_∞, ε) ≤ N^ext(A, ε/2) + ∑_{l < m(ε)} N^ext(F^l, d_∞, ε)`.
  Long words are `ε/2`-close to constant maps landing in `A` (whence external centers), short
  words are covered separately.
-/

open scoped NNReal ENNReal UniformConvergence
open Metric

open FoML.ToMathlib

namespace LeanDeepgen

section WordLemmas

variable {X : Type*} {F : Set (X → X)}

@[blueprint "lem:mem-wordball-iff-words"
  (statement := /-- $f \in B(k,F)$ if and only if $f \in F^l$ for some $l \le k$. -/)]
theorem mem_wordBall_iff {k : ℕ} {f : X → X} :
    f ∈ wordBall F k ↔ ∃ l, l ≤ k ∧ f ∈ words F l := by
  /-- Induction on $k$ using $B(k+1,F) = B(k,F) \cup F^{k+1}$. -/
  induction k with
  | zero =>
    constructor
    · intro hf
      exact ⟨0, le_rfl, hf⟩
    · rintro ⟨l, hl, hf⟩
      rw [Nat.le_zero.1 hl] at hf
      exact hf
  | succ k ih =>
    rw [wordBall_succ_eq_union_words, Set.mem_union, ih]
    constructor
    · rintro (⟨l, hl, hf⟩ | hf)
      · exact ⟨l, Nat.le_succ_of_le hl, hf⟩
      · exact ⟨k + 1, le_rfl, hf⟩
    · rintro ⟨l, hl, hf⟩
      rcases Nat.lt_or_ge l (k + 1) with h | h
      · exact Or.inl ⟨l, Nat.lt_succ_iff.1 h, hf⟩
      · exact Or.inr (by rwa [show l = k + 1 by omega] at hf)

@[blueprint "lem:words-add-decomp"
  (statement := /-- Every word of length $n + L$ factors as $w = w_2 \circ w_1$ with
    $w_2 \in F^n$ and $w_1 \in F^L$. -/)]
theorem exists_comp_of_mem_words_add {n L : ℕ} {w : X → X} (hw : w ∈ words F (n + L)) :
    ∃ w₂ ∈ words F n, ∃ w₁ ∈ words F L, w = w₂ ∘ w₁ := by
  /-- Induction on $n$: for $n = 0$ take $w_2 = \mathrm{id}$; for $w = a \circ b$ with $a \in F$,
    $b \in F^{n+L}$, factor $b = b_2 \circ b_1$ and take $w_2 = a \circ b_2$. -/
  induction n generalizing w with
  | zero =>
    rw [zero_add] at hw
    exact ⟨id, rfl, w, hw, rfl⟩
  | succ n ih =>
    rw [show n + 1 + L = n + L + 1 by omega] at hw
    obtain ⟨a, ha, b, hb, rfl⟩ := hw
    obtain ⟨b₂, hb₂, b₁, hb₁, rfl⟩ := ih hb
    exact ⟨a ∘ b₂, ⟨a, ha, b₂, hb₂, rfl⟩, b₁, hb₁, rfl⟩

@[blueprint "lem:words-invariant"
  (statement := /-- If $f(A) \subseteq A$ for every $f \in F$, then $w(a) \in A$ for every word
    $w \in F^m$ and every $a \in A$. -/)]
theorem apply_mem_of_mem_words {A : Set X} (hA : ∀ f ∈ F, f '' A ⊆ A) {m : ℕ} {w : X → X}
    (hw : w ∈ words F m) {a : X} (ha : a ∈ A) : w a ∈ A := by
  /-- Induction on $m$. -/
  induction m generalizing w with
  | zero =>
    simp only [words, Set.mem_singleton_iff] at hw
    subst hw
    exact ha
  | succ m ih =>
    obtain ⟨g, hg, b, hb, rfl⟩ := hw
    exact hA g hg ⟨b a, ih hb, rfl⟩

end WordLemmas

section Lipschitz

variable {X : Type*} [PseudoEMetricSpace X] {F : Set (X → X)}

@[blueprint "lem:words-lipschitz-pow"
  (statement := /-- If every $f \in F$ is $c$-Lipschitz then every word $w \in F^m$ is
    $c^m$-Lipschitz. -/)]
theorem lipschitzWith_pow_of_mem_words {c : ℝ≥0} (hF : ∀ f ∈ F, LipschitzWith c f) {m : ℕ}
    {w : X → X} (hw : w ∈ words F m) : LipschitzWith (c ^ m) w := by
  /-- Induction on $m$; Lipschitz constants multiply under composition. -/
  induction m generalizing w with
  | zero =>
    simp only [words, Set.mem_singleton_iff] at hw
    subst hw
    simpa using LipschitzWith.id
  | succ m ih =>
    obtain ⟨a, ha, b, hb, rfl⟩ := hw
    rw [pow_succ']
    exact (hF a ha).comp (ih hb)

@[blueprint "lem:wordball-lipschitz-one"
  (statement := /-- If the generators are non-expanding ($1$-Lipschitz) then every element of
    $B(k,F)$ is non-expanding. -/)]
theorem lipschitzWith_one_of_mem_wordBall (hF : ∀ f ∈ F, LipschitzWith 1 f) {k : ℕ} {w : X → X}
    (hw : w ∈ wordBall F k) : LipschitzWith 1 w := by
  /-- Induction on $k$; $\mathrm{id}$ is $1$-Lipschitz and $1 \cdot 1 = 1$. -/
  induction k generalizing w with
  | zero =>
    simp only [wordBall_zero, Set.mem_singleton_iff] at hw
    subst hw
    exact LipschitzWith.id
  | succ k ih =>
    rcases hw with hw | ⟨a, ha, b, hb, rfl⟩
    · exact ih hw
    · simpa using (hF a ha).comp (ih hb)

@[blueprint "lem:semigroup-closure-lipschitz-one"
  (statement := /-- If the generators are non-expanding then the whole semigroup
    $\langle F \rangle$ is non-expanding: $\mathrm{lip}\,F \le 1$ implies
    $\mathrm{lip}\,\langle F \rangle \le 1$. -/)]
theorem lipschitzWith_one_of_mem_semigroupClosure (hF : ∀ f ∈ F, LipschitzWith 1 f) {w : X → X}
    (hw : w ∈ semigroupClosure F) : LipschitzWith 1 w := by
  /-- $\langle F \rangle = \bigcup_k B(k,F)$. -/
  obtain ⟨k, hk⟩ := Set.mem_iUnion.1 hw
  exact lipschitzWith_one_of_mem_wordBall hF hk

end Lipschitz

section P1

variable {X : Type*} [PseudoMetricSpace X] {F : Set (X → X)}

@[blueprint "cond:p1"
  (statement := /-- \textbf{(P1: equicontinuous semigroup on a compact domain saturates,
    hypothesis 1.)} Assume $\mathcal X$ is compact and the semigroup $\langle F \rangle$ is
    precompact (totally bounded) in $d_\infty$. Then, with
    $G := \overline{\langle F\rangle}^{d_\infty}$, for all $\varepsilon > 0$ and all $k$,
    $$N^{\mathrm{ext}}(B(k,F), d_\infty, \varepsilon) \le N^{\mathrm{ext}}(G, d_\infty, \varepsilon)
      < \infty,$$
    hence no dependence on $k$.
    (Compactness of $\mathcal X$ is not needed for this hypothesis.) -/)]
theorem cond_p1_of_totallyBounded (h : TotallyBounded (α := UnifMaps X) (semigroupClosure F))
    (ε : ℝ≥0) (hε : 0 < ε) (k : ℕ) :
    externalCoveringNumber (X := UnifMaps X) ε (wordBall F k) ≤
        externalCoveringNumber (X := UnifMaps X) ε
          (closure (X := UnifMaps X) (semigroupClosure F)) ∧
      externalCoveringNumber (X := UnifMaps X) ε
        (closure (X := UnifMaps X) (semigroupClosure F)) ≠ ⊤ := by
  /-- $B(k,F) \subseteq G$ and monotonicity of the external covering number; $G$ is totally
    bounded as the closure of a totally bounded set, so its covering number is finite. -/
  refine ⟨externalCoveringNumber_mono_set
    (subset_semigroupClosure.trans (subset_closure (X := UnifMaps X))), ?_⟩
  exact externalCoveringNumber_ne_top_of_totallyBounded h.closure hε

@[blueprint "cond:p1-2a"
  (statement := /-- \textbf{(P1, hypothesis 2a.)} Assume $\mathcal X$ is compact and the
    semigroup $\langle F \rangle$ is equicontinuous. Then for all $\varepsilon > 0$ and all $k$,
    $N^{\mathrm{ext}}(B(k,F), d_\infty, \varepsilon)
      \le N^{\mathrm{ext}}(\overline{\langle F\rangle}, d_\infty, \varepsilon) < \infty$. -/)]
theorem cond_p1_of_equicontinuous [CompactSpace X]
    (h : Equicontinuous (fun f : semigroupClosure F => (f : X → X)))
    (ε : ℝ≥0) (hε : 0 < ε) (k : ℕ) :
    externalCoveringNumber (X := UnifMaps X) ε (wordBall F k) ≤
        externalCoveringNumber (X := UnifMaps X) ε
          (closure (X := UnifMaps X) (semigroupClosure F)) ∧
      externalCoveringNumber (X := UnifMaps X) ε
        (closure (X := UnifMaps X) (semigroupClosure F)) ≠ ⊤ :=
  /- Arzelà–Ascoli (`thm:caa`): equicontinuous implies totally bounded in $d_\infty$. -/
  cond_p1_of_totallyBounded (totallyBounded_unifMaps_of_equicontinuous h) ε hε k

@[blueprint "cond:p1-2b"
  (statement := /-- \textbf{(P1, hypothesis 2b.)} Assume $\mathcal X$ is compact and the
    semigroup $\langle F \rangle$ is uniformly Lipschitz: every $g \in \langle F \rangle$ is
    $K$-Lipschitz for a common $K$. Then for all $\varepsilon > 0$ and all $k$,
    $N^{\mathrm{ext}}(B(k,F), d_\infty, \varepsilon)
      \le N^{\mathrm{ext}}(\overline{\langle F\rangle}, d_\infty, \varepsilon) < \infty$. -/)]
theorem cond_p1_of_uniformLipschitz [CompactSpace X] (K : ℝ≥0)
    (h : ∀ g ∈ semigroupClosure F, LipschitzWith K g) (ε : ℝ≥0) (hε : 0 < ε) (k : ℕ) :
    externalCoveringNumber (X := UnifMaps X) ε (wordBall F k) ≤
        externalCoveringNumber (X := UnifMaps X) ε
          (closure (X := UnifMaps X) (semigroupClosure F)) ∧
      externalCoveringNumber (X := UnifMaps X) ε
        (closure (X := UnifMaps X) (semigroupClosure F)) ≠ ⊤ :=
  /- A uniform Lipschitz bound is a common modulus of continuity, hence gives (uniform)
    equicontinuity. -/
  cond_p1_of_equicontinuous
    ((LipschitzWith.uniformEquicontinuous (fun g : semigroupClosure F => (g : X → X)) K
      fun g => h g g.2).equicontinuous) ε hε k

@[blueprint "cond:p1-2c"
  (statement := /-- \textbf{(P1, hypothesis 2c.)} Assume $\mathcal X$ is compact and the
    generators are non-expanding: $\mathrm{lip}\,F \le 1$. Then for all $\varepsilon > 0$ and all
    $k$, $N^{\mathrm{ext}}(B(k,F), d_\infty, \varepsilon)
      \le N^{\mathrm{ext}}(\overline{\langle F\rangle}, d_\infty, \varepsilon) < \infty$. -/)]
theorem cond_p1_of_nonexpanding [CompactSpace X] (h : ∀ f ∈ F, LipschitzWith 1 f)
    (ε : ℝ≥0) (hε : 0 < ε) (k : ℕ) :
    externalCoveringNumber (X := UnifMaps X) ε (wordBall F k) ≤
        externalCoveringNumber (X := UnifMaps X) ε
          (closure (X := UnifMaps X) (semigroupClosure F)) ∧
      externalCoveringNumber (X := UnifMaps X) ε
        (closure (X := UnifMaps X) (semigroupClosure F)) ≠ ⊤ :=
  /- Non-expanding generators generate a non-expanding semigroup. -/
  cond_p1_of_uniformLipschitz 1 (fun _ hg => lipschitzWith_one_of_mem_semigroupClosure h hg) ε hε k

end P1

section P1Contraction

variable {X : Type*} [PseudoMetricSpace X] {F : Set (X → X)}

@[blueprint "lem:p1ucont-pow-diam-le"
  (statement := /-- If $0 < c < 1$, $\varepsilon > 0$ and $m(\varepsilon) \le n + L$ then
    $c^n \,\mathrm{diam}(K) \le \varepsilon/2$. -/)]
theorem pow_mul_diam_le_of_memoryLength_le {c : ℝ≥0} (hc0 : 0 < c) (hc1 : c < 1) {L : ℕ}
    {K : Set X} {ε : ℝ≥0} (hε : 0 < ε) {n : ℕ} (hn : memoryLength c L K ε ≤ n + L) :
    (c : ℝ) ^ n * Metric.diam K ≤ (ε : ℝ) / 2 := by
  /-- If $\mathrm{diam}(K) = 0$ this is trivial. Otherwise
    $\log_{1/c}(2\,\mathrm{diam}(K)/\varepsilon) \le \lceil \cdot \rceil \le n$, i.e.
    $2\,\mathrm{diam}(K)/\varepsilon \le (1/c)^n$, which rearranges to the claim. -/
  have hc0' : (0 : ℝ) < c := hc0
  have hc1' : (c : ℝ) < 1 := by exact_mod_cast hc1
  have hε' : (0 : ℝ) < ε := hε
  have hD : 0 ≤ Metric.diam K := Metric.diam_nonneg
  rcases hD.eq_or_lt with hD0 | hD0
  · rw [← hD0, mul_zero]
    positivity
  · have hb : 1 < 1 / (c : ℝ) := one_lt_one_div hc0' hc1'
    have hx : 0 < 2 * Metric.diam K / (ε : ℝ) := by positivity
    have hn' : L + ⌈Real.logb (1 / (c : ℝ)) (2 * Metric.diam K / (ε : ℝ))⌉₊ ≤ n + L := hn
    have hceil : ⌈Real.logb (1 / (c : ℝ)) (2 * Metric.diam K / (ε : ℝ))⌉₊ ≤ n := by omega
    have hlog : Real.logb (1 / (c : ℝ)) (2 * Metric.diam K / (ε : ℝ)) ≤ (n : ℝ) :=
      (Nat.le_ceil _).trans (by exact_mod_cast hceil)
    rw [Real.logb_le_iff_le_rpow hb hx, Real.rpow_natCast, one_div_pow,
      div_le_div_iff₀ hε' (by positivity)] at hlog
    linarith

@[blueprint "lem:p1ucont-long-word-close-to-const"
  (statement := /-- (Long words are almost constant.) Under the hypotheses of `cond:p1-ucont`,
    for every word $w \in F^l$ with $l \ge m(\varepsilon)$ and all $x, y \in \mathcal X$,
    $$d(w(x), w(y)) \le c^{\,l-L}\,\mathrm{diam}(K) \le \varepsilon/2 .$$
    In particular $d_\infty(w, \mathrm{const}_{w(a_0)}) \le \varepsilon/2$ for every
    $a_0$. -/)]
theorem edist_apply_le_of_memoryLength_le {c : ℝ≥0} (hF : ∀ f ∈ F, LipschitzWith c f)
    (hc0 : 0 < c) (hc1 : c < 1) {L : ℕ} {K : Set X} (hK : Bornology.IsBounded K)
    (hKL : ∀ f ∈ words F L, Set.range f ⊆ K) {ε : ℝ≥0} (hε : 0 < ε) {l : ℕ}
    (hl : memoryLength c L K ε ≤ l) {w : X → X} (hw : w ∈ words F l) (x y : X) :
    edist (w x) (w y) ≤ ((ε / 2 : ℝ≥0) : ℝ≥0∞) := by
  /-- Write $l = n + L$ and $w = w_2 \circ w_1$ with $w_2 \in F^n$ ($c^n$-Lipschitz) and
    $w_1 \in F^L$ (with values in $K$). Then
    $d(w(x), w(y)) \le c^n d(w_1(x), w_1(y)) \le c^n \mathrm{diam}(K) \le \varepsilon/2$. -/
  have hLl : L ≤ l := le_trans (Nat.le_add_right L _) hl
  obtain ⟨n, rfl⟩ : ∃ n, l = n + L := ⟨l - L, by omega⟩
  obtain ⟨w₂, hw₂, w₁, hw₁, rfl⟩ := exists_comp_of_mem_words_add hw
  have hlip : LipschitzWith (c ^ n) w₂ := lipschitzWith_pow_of_mem_words hF hw₂
  have hx : w₁ x ∈ K := hKL w₁ hw₁ ⟨x, rfl⟩
  have hy : w₁ y ∈ K := hKL w₁ hw₁ ⟨y, rfl⟩
  have hreal : (c : ℝ) ^ n * Metric.diam K ≤ (ε : ℝ) / 2 :=
    pow_mul_diam_le_of_memoryLength_le hc0 hc1 hε hl
  calc edist ((w₂ ∘ w₁) x) ((w₂ ∘ w₁) y)
      ≤ ((c ^ n : ℝ≥0) : ℝ≥0∞) * edist (w₁ x) (w₁ y) := hlip.edist_le_mul _ _
    _ ≤ ((c ^ n : ℝ≥0) : ℝ≥0∞) * Metric.ediam K := by
        gcongr
        exact edist_le_ediam_of_mem hx hy
    _ = ENNReal.ofReal ((c : ℝ) ^ n * Metric.diam K) := by
        rw [ENNReal.coe_pow, ENNReal.ofReal_mul (by positivity), ENNReal.ofReal_pow c.coe_nonneg,
          ENNReal.ofReal_coe_nnreal, Metric.diam, ENNReal.ofReal_toReal hK.ediam_ne_top]
    _ ≤ ENNReal.ofReal ((ε : ℝ) / 2) := ENNReal.ofReal_le_ofReal hreal
    _ = ((ε / 2 : ℝ≥0) : ℝ≥0∞) := by
        rw [← ENNReal.ofReal_coe_nnreal, NNReal.coe_div, NNReal.coe_ofNat]

@[blueprint "lem:p1ucont-long-words"
  (statement := /-- (Long words.) Under the hypotheses of `cond:p1-ucont`, the set of all words
    of length $\ge m(\varepsilon)$ satisfies
    $$N^{\mathrm{ext}}\Bigl(\bigcup_{l \ge m(\varepsilon)} F^l, d_\infty, \varepsilon\Bigr)
      \le N^{\mathrm{ext}}(A, d, \varepsilon/2) .$$
    Indeed each such word $w$ is $\varepsilon/2$-close to the constant map
    $\mathrm{const}_{w(a_0)}$ with $w(a_0) \in A$, so the constant maps at the points of an
    $\varepsilon/2$-net of $A$ form an $\varepsilon$-cover. -/)]
theorem externalCoveringNumber_longWords_le {c : ℝ≥0} (hF : ∀ f ∈ F, LipschitzWith c f)
    (hc0 : 0 < c) (hc1 : c < 1) {A : Set X} (hA : A.Nonempty) (hAinv : ∀ f ∈ F, f '' A ⊆ A)
    {L : ℕ} {K : Set X} (hK : Bornology.IsBounded K) (hKL : ∀ f ∈ words F L, Set.range f ⊆ K)
    {ε : ℝ≥0} (hε : 0 < ε) :
    externalCoveringNumber (X := UnifMaps X) ε
        {w | ∃ l, memoryLength c L K ε ≤ l ∧ w ∈ words F l} ≤
      externalCoveringNumber (ε / 2) A := by
  /-- Take a minimal $\varepsilon/2$-cover $C$ of $A$; for a long word $w$ pick $q \in C$ with
    $d(w(a_0), q) \le \varepsilon/2$; then $d(w(x), q) \le d(w(x), w(a_0)) + d(w(a_0), q)
    \le \varepsilon$ for every $x$, so $\{\mathrm{const}_q : q \in C\}$ is an
    $\varepsilon$-cover. -/
  obtain ⟨a₀, ha₀⟩ := hA
  obtain ⟨C, hC, hCe⟩ := exists_isCover_encard_eq_externalCoveringNumber (ε / 2) A
  have hcover : IsCover (X := UnifMaps X) ε {w | ∃ l, memoryLength c L K ε ≤ l ∧ w ∈ words F l}
      (toUnifMaps '' ((fun q : X => Function.const X q) '' C)) := by
    rintro w ⟨l, hl, hw⟩
    have hwa : w a₀ ∈ A := apply_mem_of_mem_words hAinv hw ha₀
    obtain ⟨q, hqC, hq⟩ := hC hwa
    refine ⟨toUnifMaps (Function.const X q), ⟨Function.const X q, ⟨q, hqC, rfl⟩, rfl⟩, ?_⟩
    change edist (toUnifMaps w) (toUnifMaps (Function.const X q)) ≤ ε
    refine UniformFun.edist_le.2 fun x => ?_
    change edist (w x) q ≤ (ε : ℝ≥0∞)
    calc edist (w x) q ≤ edist (w x) (w a₀) + edist (w a₀) q := edist_triangle _ _ _
      _ ≤ ((ε / 2 : ℝ≥0) : ℝ≥0∞) + ((ε / 2 : ℝ≥0) : ℝ≥0∞) :=
          add_le_add (edist_apply_le_of_memoryLength_le hF hc0 hc1 hK hKL hε hl hw x a₀) hq
      _ = ε := by rw [← ENNReal.coe_add, add_halves]
  rw [← hCe]
  exact hcover.externalCoveringNumber_le_encard.trans
    ((Set.encard_image_le _ _).trans (Set.encard_image_le _ _))

@[blueprint "lem:p1ucont-short-words"
  (statement := /-- (Short words; subadditivity over finitely many sets.) For a finite family
    $(A_i)_{i \in s}$, $N^{\mathrm{ext}}\bigl(\bigcup_{i \in s} A_i, \varepsilon\bigr)
    \le \sum_{i \in s} N^{\mathrm{ext}}(A_i, \varepsilon)$. Applied to
    $A_l = F^l$, $l < m(\varepsilon)$, this covers the short words. -/)]
theorem externalCoveringNumber_biUnion_le {Y : Type*} [PseudoEMetricSpace Y] {ι : Type*}
    (ε : ℝ≥0) (s : Finset ι) (A : ι → Set Y) :
    externalCoveringNumber ε (⋃ i ∈ s, A i) ≤ ∑ i ∈ s, externalCoveringNumber ε (A i) := by
  /-- Induction on the finite index set using `lem:subadditivity`. -/
  classical
  induction s using Finset.induction_on with
  | empty => simp
  | insert i s hi ih =>
    rw [Finset.set_biUnion_insert, Finset.sum_insert hi]
    exact (externalCoveringNumber_union_le ε _ _).trans (add_le_add le_rfl ih)

@[blueprint "cond:p1-ucont"
  (statement := /-- \textbf{(P1': contraction to a compact invariant set.)} Assume
    \begin{enumerate}
    \item (uniform contraction) every $f \in F$ is $c$-Lipschitz with $0 < c < 1$;
    \item (invariant set) there is a nonempty $F$-invariant set $A \subseteq \mathcal X$
      ($f(A) \subseteq A$ for all $f \in F$);
    \item (bounded absorbing set) there are $L \in \mathbb N$ and a bounded set
      $K \subseteq \mathcal X$ with $f(\mathcal X) \subseteq K$ for every word $f \in F^L$ of
      length $L$.
    \end{enumerate}
    Then for every $\varepsilon > 0$, with
    $m(\varepsilon) := L + \lceil \log_{1/c}(2\,\mathrm{diam}(K)/\varepsilon) \rceil$, for
    \emph{every} $k \ge 0$,
    $$N^{\mathrm{ext}}(B(k,F), d_\infty, \varepsilon) \le N^{\mathrm{ext}}(A, d, \varepsilon/2)
      + \sum_{l=0}^{m(\varepsilon)-1} N^{\mathrm{ext}}(F^l, d_\infty, \varepsilon) .$$
    In particular the right-hand side is independent of $k$.
    (This generalizes the paper, which assumes $A$ compact, $K$ compact and
    $k \ge m(\varepsilon)$: the proof uses of $A$ only that it is nonempty and invariant, of $K$
    only its boundedness, and the bound holds for every $k$. The right-hand side is finite
    whenever each $N^{\mathrm{ext}}(F^l, d_\infty, \varepsilon)$, $l < m(\varepsilon)$, is
    finite, which the paper does not assume.) -/)]
theorem cond_p1_ucont {c : ℝ≥0} (hF : ∀ f ∈ F, LipschitzWith c f) (hc0 : 0 < c) (hc1 : c < 1)
    {A : Set X} (hA : A.Nonempty) (hAinv : ∀ f ∈ F, f '' A ⊆ A)
    {L : ℕ} {K : Set X} (hK : Bornology.IsBounded K) (hKL : ∀ f ∈ words F L, Set.range f ⊆ K)
    (ε : ℝ≥0) (hε : 0 < ε) (k : ℕ) :
    externalCoveringNumber (X := UnifMaps X) ε (wordBall F k) ≤
      externalCoveringNumber (ε / 2) A +
        ∑ l ∈ Finset.range (memoryLength c L K ε),
          externalCoveringNumber (X := UnifMaps X) ε (words F l) := by
  /-- $B(k,F) \subseteq \bigcup_{l \ge m(\varepsilon)} F^l \cup \bigcup_{l < m(\varepsilon)} F^l$;
    apply monotonicity, subadditivity, `lem:p1ucont-long-words` and
    `lem:p1ucont-short-words`. -/
  set m := memoryLength c L K ε with hm
  have hsub : wordBall F k ⊆
      {w | ∃ l, m ≤ l ∧ w ∈ words F l} ∪ ⋃ l ∈ Finset.range m, words F l := by
    intro w hw
    obtain ⟨l, _, hwl⟩ := mem_wordBall_iff.1 hw
    by_cases hlm : m ≤ l
    · exact Or.inl ⟨l, hlm, hwl⟩
    · exact Or.inr (Set.mem_iUnion₂.2 ⟨l, Finset.mem_range.2 (not_le.1 hlm), hwl⟩)
  calc externalCoveringNumber (X := UnifMaps X) ε (wordBall F k)
      ≤ externalCoveringNumber (X := UnifMaps X) ε
          ({w | ∃ l, m ≤ l ∧ w ∈ words F l} ∪ ⋃ l ∈ Finset.range m, words F l) :=
        externalCoveringNumber_mono_set hsub
    _ ≤ externalCoveringNumber (X := UnifMaps X) ε {w | ∃ l, m ≤ l ∧ w ∈ words F l} +
          externalCoveringNumber (X := UnifMaps X) ε (⋃ l ∈ Finset.range m, words F l) :=
        externalCoveringNumber_union_le ε _ _
    _ ≤ _ := add_le_add
        (externalCoveringNumber_longWords_le hF hc0 hc1 hA hAinv hK hKL hε)
        (externalCoveringNumber_biUnion_le (Y := UnifMaps X) ε (Finset.range m) (words F))

end P1Contraction

end LeanDeepgen
